name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --frozen-lockfile
    - run: yarn test --coverage
    - run: cat coverage/lcov.info | yarn coveralls 
